### ISSUE TITLE
Editor tracking issue

### ISSUE THREAD

**Issue by mbrea-c** [mbrea-c/bevy_animation_graph#25]
This issue exists to keep track of tasks related to the first editor release.

* [x] Core functionality: #24 
  * [x] Load and display graphs
  * [x] Save graphs to disk
  * [x] Position and  move nodes
  * [x] Add nodes
  * [x] Remove nodes
  * [x] Rename nodes
  * [x] Add edges
  * [x] Remove edges
  * [x] Creating new graph
  * [x] Live preview animated scene
  * [x] Inspector for node fields
  * [x] Edit graph properties (inputs and outputs, default values)
    * [x] Edit input pose, output pose and output parameter specs
    * [x] Edit default input parameters: currently missing editor UI for bonemasks
* [x] Update docs  #29 
* [x] Order preserving input/output maps
* [x] Error handling: #22 PR: #26
  * [x] Library should avoid panics during graph evaluation, instead propagating an error
  * [x] Editor should not crash on graph evaluation error, instead display error

### Known bugs
* [x] Top node selection is unstable while doing a box selection
