### ISSUE TITLE
0.2 Release checklist

### ISSUE THREAD

**Issue by mbrea-c** [mbrea-c/bevy_animation_graph#30]
- [x] Update version
- [x] Update workspace dependency versions
- [x] Publish library crate
- [x] Publish editor crate
- [x] Add editor crate tracking labels to README
